services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS} --save 60 1 #save cmd for persistence
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      #- ./redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    #restart: always

  consumer:
    image: "jhawk7/go-counter-consumer"
    build: 
      context: ./ #dockerfile context will be relative to this file's dir
      dockerfile: ./counter-consumer/Dockerfile
    ports:
      - "8181:8888"
    env_file:
      - .env
    #restart: always
    depends_on:
      - redis
  
  producer:
    image: "jhawk7/go-counter-producer"
    build:
      context: ./ 
      dockerfile: ./counter-producer/Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - .env
    #restart: always
    depends_on:
      - redis
